// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/blockrepo.proto

package jelectrum.proto;

public final class Blockrepo {
  private Blockrepo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BitcoinBlockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jelectrum.proto.BitcoinBlock)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 height = 1;</code>
     */
    boolean hasHeight();
    /**
     * <code>required int32 height = 1;</code>
     */
    int getHeight();

    /**
     * <code>required string hash = 2;</code>
     */
    boolean hasHash();
    /**
     * <code>required string hash = 2;</code>
     */
    java.lang.String getHash();
    /**
     * <code>required string hash = 2;</code>
     */
    com.google.protobuf.ByteString
        getHashBytes();

    /**
     * <code>required bytes block_data = 3;</code>
     */
    boolean hasBlockData();
    /**
     * <code>required bytes block_data = 3;</code>
     */
    com.google.protobuf.ByteString getBlockData();
  }
  /**
   * Protobuf type {@code jelectrum.proto.BitcoinBlock}
   */
  public  static final class BitcoinBlock extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:jelectrum.proto.BitcoinBlock)
      BitcoinBlockOrBuilder {
    // Use BitcoinBlock.newBuilder() to construct.
    private BitcoinBlock(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private BitcoinBlock() {
      height_ = 0;
      hash_ = "";
      blockData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BitcoinBlock(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              height_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              hash_ = bs;
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              blockData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jelectrum.proto.Blockrepo.internal_static_jelectrum_proto_BitcoinBlock_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jelectrum.proto.Blockrepo.internal_static_jelectrum_proto_BitcoinBlock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jelectrum.proto.Blockrepo.BitcoinBlock.class, jelectrum.proto.Blockrepo.BitcoinBlock.Builder.class);
    }

    private int bitField0_;
    public static final int HEIGHT_FIELD_NUMBER = 1;
    private int height_;
    /**
     * <code>required int32 height = 1;</code>
     */
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 height = 1;</code>
     */
    public int getHeight() {
      return height_;
    }

    public static final int HASH_FIELD_NUMBER = 2;
    private volatile java.lang.Object hash_;
    /**
     * <code>required string hash = 2;</code>
     */
    public boolean hasHash() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string hash = 2;</code>
     */
    public java.lang.String getHash() {
      java.lang.Object ref = hash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          hash_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string hash = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHashBytes() {
      java.lang.Object ref = hash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BLOCK_DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString blockData_;
    /**
     * <code>required bytes block_data = 3;</code>
     */
    public boolean hasBlockData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes block_data = 3;</code>
     */
    public com.google.protobuf.ByteString getBlockData() {
      return blockData_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHeight()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHash()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBlockData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, height_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, hash_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, blockData_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, height_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, hash_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, blockData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static jelectrum.proto.Blockrepo.BitcoinBlock parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jelectrum.proto.Blockrepo.BitcoinBlock parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jelectrum.proto.Blockrepo.BitcoinBlock parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jelectrum.proto.Blockrepo.BitcoinBlock parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jelectrum.proto.Blockrepo.BitcoinBlock parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jelectrum.proto.Blockrepo.BitcoinBlock parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static jelectrum.proto.Blockrepo.BitcoinBlock parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static jelectrum.proto.Blockrepo.BitcoinBlock parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static jelectrum.proto.Blockrepo.BitcoinBlock parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jelectrum.proto.Blockrepo.BitcoinBlock parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(jelectrum.proto.Blockrepo.BitcoinBlock prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jelectrum.proto.BitcoinBlock}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jelectrum.proto.BitcoinBlock)
        jelectrum.proto.Blockrepo.BitcoinBlockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jelectrum.proto.Blockrepo.internal_static_jelectrum_proto_BitcoinBlock_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jelectrum.proto.Blockrepo.internal_static_jelectrum_proto_BitcoinBlock_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jelectrum.proto.Blockrepo.BitcoinBlock.class, jelectrum.proto.Blockrepo.BitcoinBlock.Builder.class);
      }

      // Construct using jelectrum.proto.Blockrepo.BitcoinBlock.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        height_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        hash_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        blockData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jelectrum.proto.Blockrepo.internal_static_jelectrum_proto_BitcoinBlock_descriptor;
      }

      public jelectrum.proto.Blockrepo.BitcoinBlock getDefaultInstanceForType() {
        return jelectrum.proto.Blockrepo.BitcoinBlock.getDefaultInstance();
      }

      public jelectrum.proto.Blockrepo.BitcoinBlock build() {
        jelectrum.proto.Blockrepo.BitcoinBlock result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public jelectrum.proto.Blockrepo.BitcoinBlock buildPartial() {
        jelectrum.proto.Blockrepo.BitcoinBlock result = new jelectrum.proto.Blockrepo.BitcoinBlock(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.height_ = height_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.hash_ = hash_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.blockData_ = blockData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jelectrum.proto.Blockrepo.BitcoinBlock) {
          return mergeFrom((jelectrum.proto.Blockrepo.BitcoinBlock)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jelectrum.proto.Blockrepo.BitcoinBlock other) {
        if (other == jelectrum.proto.Blockrepo.BitcoinBlock.getDefaultInstance()) return this;
        if (other.hasHeight()) {
          setHeight(other.getHeight());
        }
        if (other.hasHash()) {
          bitField0_ |= 0x00000002;
          hash_ = other.hash_;
          onChanged();
        }
        if (other.hasBlockData()) {
          setBlockData(other.getBlockData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHeight()) {
          return false;
        }
        if (!hasHash()) {
          return false;
        }
        if (!hasBlockData()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jelectrum.proto.Blockrepo.BitcoinBlock parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jelectrum.proto.Blockrepo.BitcoinBlock) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int height_ ;
      /**
       * <code>required int32 height = 1;</code>
       */
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 height = 1;</code>
       */
      public int getHeight() {
        return height_;
      }
      /**
       * <code>required int32 height = 1;</code>
       */
      public Builder setHeight(int value) {
        bitField0_ |= 0x00000001;
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 height = 1;</code>
       */
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000001);
        height_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object hash_ = "";
      /**
       * <code>required string hash = 2;</code>
       */
      public boolean hasHash() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string hash = 2;</code>
       */
      public java.lang.String getHash() {
        java.lang.Object ref = hash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            hash_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string hash = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHashBytes() {
        java.lang.Object ref = hash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string hash = 2;</code>
       */
      public Builder setHash(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        hash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string hash = 2;</code>
       */
      public Builder clearHash() {
        bitField0_ = (bitField0_ & ~0x00000002);
        hash_ = getDefaultInstance().getHash();
        onChanged();
        return this;
      }
      /**
       * <code>required string hash = 2;</code>
       */
      public Builder setHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        hash_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString blockData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes block_data = 3;</code>
       */
      public boolean hasBlockData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes block_data = 3;</code>
       */
      public com.google.protobuf.ByteString getBlockData() {
        return blockData_;
      }
      /**
       * <code>required bytes block_data = 3;</code>
       */
      public Builder setBlockData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        blockData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes block_data = 3;</code>
       */
      public Builder clearBlockData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        blockData_ = getDefaultInstance().getBlockData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:jelectrum.proto.BitcoinBlock)
    }

    // @@protoc_insertion_point(class_scope:jelectrum.proto.BitcoinBlock)
    private static final jelectrum.proto.Blockrepo.BitcoinBlock DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new jelectrum.proto.Blockrepo.BitcoinBlock();
    }

    public static jelectrum.proto.Blockrepo.BitcoinBlock getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<BitcoinBlock>
        PARSER = new com.google.protobuf.AbstractParser<BitcoinBlock>() {
      public BitcoinBlock parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new BitcoinBlock(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<BitcoinBlock> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BitcoinBlock> getParserForType() {
      return PARSER;
    }

    public jelectrum.proto.Blockrepo.BitcoinBlock getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BitcoinBlockPackOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jelectrum.proto.BitcoinBlockPack)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string new_head_hash = 1;</code>
     */
    boolean hasNewHeadHash();
    /**
     * <code>required string new_head_hash = 1;</code>
     */
    java.lang.String getNewHeadHash();
    /**
     * <code>required string new_head_hash = 1;</code>
     */
    com.google.protobuf.ByteString
        getNewHeadHashBytes();

    /**
     * <code>required int32 start_height = 2;</code>
     */
    boolean hasStartHeight();
    /**
     * <code>required int32 start_height = 2;</code>
     */
    int getStartHeight();

    /**
     * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
     */
    java.util.List<jelectrum.proto.Blockrepo.BitcoinBlock> 
        getBlocksList();
    /**
     * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
     */
    jelectrum.proto.Blockrepo.BitcoinBlock getBlocks(int index);
    /**
     * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
     */
    int getBlocksCount();
    /**
     * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
     */
    java.util.List<? extends jelectrum.proto.Blockrepo.BitcoinBlockOrBuilder> 
        getBlocksOrBuilderList();
    /**
     * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
     */
    jelectrum.proto.Blockrepo.BitcoinBlockOrBuilder getBlocksOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code jelectrum.proto.BitcoinBlockPack}
   */
  public  static final class BitcoinBlockPack extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:jelectrum.proto.BitcoinBlockPack)
      BitcoinBlockPackOrBuilder {
    // Use BitcoinBlockPack.newBuilder() to construct.
    private BitcoinBlockPack(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private BitcoinBlockPack() {
      newHeadHash_ = "";
      startHeight_ = 0;
      blocks_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BitcoinBlockPack(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              newHeadHash_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              startHeight_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                blocks_ = new java.util.ArrayList<jelectrum.proto.Blockrepo.BitcoinBlock>();
                mutable_bitField0_ |= 0x00000004;
              }
              blocks_.add(input.readMessage(jelectrum.proto.Blockrepo.BitcoinBlock.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          blocks_ = java.util.Collections.unmodifiableList(blocks_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jelectrum.proto.Blockrepo.internal_static_jelectrum_proto_BitcoinBlockPack_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jelectrum.proto.Blockrepo.internal_static_jelectrum_proto_BitcoinBlockPack_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jelectrum.proto.Blockrepo.BitcoinBlockPack.class, jelectrum.proto.Blockrepo.BitcoinBlockPack.Builder.class);
    }

    private int bitField0_;
    public static final int NEW_HEAD_HASH_FIELD_NUMBER = 1;
    private volatile java.lang.Object newHeadHash_;
    /**
     * <code>required string new_head_hash = 1;</code>
     */
    public boolean hasNewHeadHash() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string new_head_hash = 1;</code>
     */
    public java.lang.String getNewHeadHash() {
      java.lang.Object ref = newHeadHash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          newHeadHash_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string new_head_hash = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNewHeadHashBytes() {
      java.lang.Object ref = newHeadHash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        newHeadHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int START_HEIGHT_FIELD_NUMBER = 2;
    private int startHeight_;
    /**
     * <code>required int32 start_height = 2;</code>
     */
    public boolean hasStartHeight() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 start_height = 2;</code>
     */
    public int getStartHeight() {
      return startHeight_;
    }

    public static final int BLOCKS_FIELD_NUMBER = 3;
    private java.util.List<jelectrum.proto.Blockrepo.BitcoinBlock> blocks_;
    /**
     * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
     */
    public java.util.List<jelectrum.proto.Blockrepo.BitcoinBlock> getBlocksList() {
      return blocks_;
    }
    /**
     * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
     */
    public java.util.List<? extends jelectrum.proto.Blockrepo.BitcoinBlockOrBuilder> 
        getBlocksOrBuilderList() {
      return blocks_;
    }
    /**
     * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
     */
    public int getBlocksCount() {
      return blocks_.size();
    }
    /**
     * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
     */
    public jelectrum.proto.Blockrepo.BitcoinBlock getBlocks(int index) {
      return blocks_.get(index);
    }
    /**
     * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
     */
    public jelectrum.proto.Blockrepo.BitcoinBlockOrBuilder getBlocksOrBuilder(
        int index) {
      return blocks_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasNewHeadHash()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStartHeight()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getBlocksCount(); i++) {
        if (!getBlocks(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, newHeadHash_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, startHeight_);
      }
      for (int i = 0; i < blocks_.size(); i++) {
        output.writeMessage(3, blocks_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, newHeadHash_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, startHeight_);
      }
      for (int i = 0; i < blocks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, blocks_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static jelectrum.proto.Blockrepo.BitcoinBlockPack parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jelectrum.proto.Blockrepo.BitcoinBlockPack parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jelectrum.proto.Blockrepo.BitcoinBlockPack parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jelectrum.proto.Blockrepo.BitcoinBlockPack parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jelectrum.proto.Blockrepo.BitcoinBlockPack parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jelectrum.proto.Blockrepo.BitcoinBlockPack parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static jelectrum.proto.Blockrepo.BitcoinBlockPack parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static jelectrum.proto.Blockrepo.BitcoinBlockPack parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static jelectrum.proto.Blockrepo.BitcoinBlockPack parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jelectrum.proto.Blockrepo.BitcoinBlockPack parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(jelectrum.proto.Blockrepo.BitcoinBlockPack prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jelectrum.proto.BitcoinBlockPack}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jelectrum.proto.BitcoinBlockPack)
        jelectrum.proto.Blockrepo.BitcoinBlockPackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jelectrum.proto.Blockrepo.internal_static_jelectrum_proto_BitcoinBlockPack_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jelectrum.proto.Blockrepo.internal_static_jelectrum_proto_BitcoinBlockPack_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jelectrum.proto.Blockrepo.BitcoinBlockPack.class, jelectrum.proto.Blockrepo.BitcoinBlockPack.Builder.class);
      }

      // Construct using jelectrum.proto.Blockrepo.BitcoinBlockPack.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBlocksFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        newHeadHash_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        startHeight_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (blocksBuilder_ == null) {
          blocks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          blocksBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jelectrum.proto.Blockrepo.internal_static_jelectrum_proto_BitcoinBlockPack_descriptor;
      }

      public jelectrum.proto.Blockrepo.BitcoinBlockPack getDefaultInstanceForType() {
        return jelectrum.proto.Blockrepo.BitcoinBlockPack.getDefaultInstance();
      }

      public jelectrum.proto.Blockrepo.BitcoinBlockPack build() {
        jelectrum.proto.Blockrepo.BitcoinBlockPack result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public jelectrum.proto.Blockrepo.BitcoinBlockPack buildPartial() {
        jelectrum.proto.Blockrepo.BitcoinBlockPack result = new jelectrum.proto.Blockrepo.BitcoinBlockPack(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.newHeadHash_ = newHeadHash_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.startHeight_ = startHeight_;
        if (blocksBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            blocks_ = java.util.Collections.unmodifiableList(blocks_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.blocks_ = blocks_;
        } else {
          result.blocks_ = blocksBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jelectrum.proto.Blockrepo.BitcoinBlockPack) {
          return mergeFrom((jelectrum.proto.Blockrepo.BitcoinBlockPack)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jelectrum.proto.Blockrepo.BitcoinBlockPack other) {
        if (other == jelectrum.proto.Blockrepo.BitcoinBlockPack.getDefaultInstance()) return this;
        if (other.hasNewHeadHash()) {
          bitField0_ |= 0x00000001;
          newHeadHash_ = other.newHeadHash_;
          onChanged();
        }
        if (other.hasStartHeight()) {
          setStartHeight(other.getStartHeight());
        }
        if (blocksBuilder_ == null) {
          if (!other.blocks_.isEmpty()) {
            if (blocks_.isEmpty()) {
              blocks_ = other.blocks_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureBlocksIsMutable();
              blocks_.addAll(other.blocks_);
            }
            onChanged();
          }
        } else {
          if (!other.blocks_.isEmpty()) {
            if (blocksBuilder_.isEmpty()) {
              blocksBuilder_.dispose();
              blocksBuilder_ = null;
              blocks_ = other.blocks_;
              bitField0_ = (bitField0_ & ~0x00000004);
              blocksBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBlocksFieldBuilder() : null;
            } else {
              blocksBuilder_.addAllMessages(other.blocks_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNewHeadHash()) {
          return false;
        }
        if (!hasStartHeight()) {
          return false;
        }
        for (int i = 0; i < getBlocksCount(); i++) {
          if (!getBlocks(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jelectrum.proto.Blockrepo.BitcoinBlockPack parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jelectrum.proto.Blockrepo.BitcoinBlockPack) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object newHeadHash_ = "";
      /**
       * <code>required string new_head_hash = 1;</code>
       */
      public boolean hasNewHeadHash() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string new_head_hash = 1;</code>
       */
      public java.lang.String getNewHeadHash() {
        java.lang.Object ref = newHeadHash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            newHeadHash_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string new_head_hash = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNewHeadHashBytes() {
        java.lang.Object ref = newHeadHash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          newHeadHash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string new_head_hash = 1;</code>
       */
      public Builder setNewHeadHash(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        newHeadHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string new_head_hash = 1;</code>
       */
      public Builder clearNewHeadHash() {
        bitField0_ = (bitField0_ & ~0x00000001);
        newHeadHash_ = getDefaultInstance().getNewHeadHash();
        onChanged();
        return this;
      }
      /**
       * <code>required string new_head_hash = 1;</code>
       */
      public Builder setNewHeadHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        newHeadHash_ = value;
        onChanged();
        return this;
      }

      private int startHeight_ ;
      /**
       * <code>required int32 start_height = 2;</code>
       */
      public boolean hasStartHeight() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 start_height = 2;</code>
       */
      public int getStartHeight() {
        return startHeight_;
      }
      /**
       * <code>required int32 start_height = 2;</code>
       */
      public Builder setStartHeight(int value) {
        bitField0_ |= 0x00000002;
        startHeight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 start_height = 2;</code>
       */
      public Builder clearStartHeight() {
        bitField0_ = (bitField0_ & ~0x00000002);
        startHeight_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<jelectrum.proto.Blockrepo.BitcoinBlock> blocks_ =
        java.util.Collections.emptyList();
      private void ensureBlocksIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          blocks_ = new java.util.ArrayList<jelectrum.proto.Blockrepo.BitcoinBlock>(blocks_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          jelectrum.proto.Blockrepo.BitcoinBlock, jelectrum.proto.Blockrepo.BitcoinBlock.Builder, jelectrum.proto.Blockrepo.BitcoinBlockOrBuilder> blocksBuilder_;

      /**
       * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
       */
      public java.util.List<jelectrum.proto.Blockrepo.BitcoinBlock> getBlocksList() {
        if (blocksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(blocks_);
        } else {
          return blocksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
       */
      public int getBlocksCount() {
        if (blocksBuilder_ == null) {
          return blocks_.size();
        } else {
          return blocksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
       */
      public jelectrum.proto.Blockrepo.BitcoinBlock getBlocks(int index) {
        if (blocksBuilder_ == null) {
          return blocks_.get(index);
        } else {
          return blocksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
       */
      public Builder setBlocks(
          int index, jelectrum.proto.Blockrepo.BitcoinBlock value) {
        if (blocksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBlocksIsMutable();
          blocks_.set(index, value);
          onChanged();
        } else {
          blocksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
       */
      public Builder setBlocks(
          int index, jelectrum.proto.Blockrepo.BitcoinBlock.Builder builderForValue) {
        if (blocksBuilder_ == null) {
          ensureBlocksIsMutable();
          blocks_.set(index, builderForValue.build());
          onChanged();
        } else {
          blocksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
       */
      public Builder addBlocks(jelectrum.proto.Blockrepo.BitcoinBlock value) {
        if (blocksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBlocksIsMutable();
          blocks_.add(value);
          onChanged();
        } else {
          blocksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
       */
      public Builder addBlocks(
          int index, jelectrum.proto.Blockrepo.BitcoinBlock value) {
        if (blocksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBlocksIsMutable();
          blocks_.add(index, value);
          onChanged();
        } else {
          blocksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
       */
      public Builder addBlocks(
          jelectrum.proto.Blockrepo.BitcoinBlock.Builder builderForValue) {
        if (blocksBuilder_ == null) {
          ensureBlocksIsMutable();
          blocks_.add(builderForValue.build());
          onChanged();
        } else {
          blocksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
       */
      public Builder addBlocks(
          int index, jelectrum.proto.Blockrepo.BitcoinBlock.Builder builderForValue) {
        if (blocksBuilder_ == null) {
          ensureBlocksIsMutable();
          blocks_.add(index, builderForValue.build());
          onChanged();
        } else {
          blocksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
       */
      public Builder addAllBlocks(
          java.lang.Iterable<? extends jelectrum.proto.Blockrepo.BitcoinBlock> values) {
        if (blocksBuilder_ == null) {
          ensureBlocksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, blocks_);
          onChanged();
        } else {
          blocksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
       */
      public Builder clearBlocks() {
        if (blocksBuilder_ == null) {
          blocks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          blocksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
       */
      public Builder removeBlocks(int index) {
        if (blocksBuilder_ == null) {
          ensureBlocksIsMutable();
          blocks_.remove(index);
          onChanged();
        } else {
          blocksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
       */
      public jelectrum.proto.Blockrepo.BitcoinBlock.Builder getBlocksBuilder(
          int index) {
        return getBlocksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
       */
      public jelectrum.proto.Blockrepo.BitcoinBlockOrBuilder getBlocksOrBuilder(
          int index) {
        if (blocksBuilder_ == null) {
          return blocks_.get(index);  } else {
          return blocksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
       */
      public java.util.List<? extends jelectrum.proto.Blockrepo.BitcoinBlockOrBuilder> 
           getBlocksOrBuilderList() {
        if (blocksBuilder_ != null) {
          return blocksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(blocks_);
        }
      }
      /**
       * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
       */
      public jelectrum.proto.Blockrepo.BitcoinBlock.Builder addBlocksBuilder() {
        return getBlocksFieldBuilder().addBuilder(
            jelectrum.proto.Blockrepo.BitcoinBlock.getDefaultInstance());
      }
      /**
       * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
       */
      public jelectrum.proto.Blockrepo.BitcoinBlock.Builder addBlocksBuilder(
          int index) {
        return getBlocksFieldBuilder().addBuilder(
            index, jelectrum.proto.Blockrepo.BitcoinBlock.getDefaultInstance());
      }
      /**
       * <code>repeated .jelectrum.proto.BitcoinBlock blocks = 3;</code>
       */
      public java.util.List<jelectrum.proto.Blockrepo.BitcoinBlock.Builder> 
           getBlocksBuilderList() {
        return getBlocksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          jelectrum.proto.Blockrepo.BitcoinBlock, jelectrum.proto.Blockrepo.BitcoinBlock.Builder, jelectrum.proto.Blockrepo.BitcoinBlockOrBuilder> 
          getBlocksFieldBuilder() {
        if (blocksBuilder_ == null) {
          blocksBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              jelectrum.proto.Blockrepo.BitcoinBlock, jelectrum.proto.Blockrepo.BitcoinBlock.Builder, jelectrum.proto.Blockrepo.BitcoinBlockOrBuilder>(
                  blocks_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          blocks_ = null;
        }
        return blocksBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:jelectrum.proto.BitcoinBlockPack)
    }

    // @@protoc_insertion_point(class_scope:jelectrum.proto.BitcoinBlockPack)
    private static final jelectrum.proto.Blockrepo.BitcoinBlockPack DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new jelectrum.proto.Blockrepo.BitcoinBlockPack();
    }

    public static jelectrum.proto.Blockrepo.BitcoinBlockPack getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<BitcoinBlockPack>
        PARSER = new com.google.protobuf.AbstractParser<BitcoinBlockPack>() {
      public BitcoinBlockPack parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new BitcoinBlockPack(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<BitcoinBlockPack> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BitcoinBlockPack> getParserForType() {
      return PARSER;
    }

    public jelectrum.proto.Blockrepo.BitcoinBlockPack getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_jelectrum_proto_BitcoinBlock_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jelectrum_proto_BitcoinBlock_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_jelectrum_proto_BitcoinBlockPack_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jelectrum_proto_BitcoinBlockPack_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025proto/blockrepo.proto\022\017jelectrum.proto" +
      "\"@\n\014BitcoinBlock\022\016\n\006height\030\001 \002(\005\022\014\n\004hash" +
      "\030\002 \002(\t\022\022\n\nblock_data\030\003 \002(\014\"n\n\020BitcoinBlo" +
      "ckPack\022\025\n\rnew_head_hash\030\001 \002(\t\022\024\n\014start_h" +
      "eight\030\002 \002(\005\022-\n\006blocks\030\003 \003(\0132\035.jelectrum." +
      "proto.BitcoinBlockB\021\n\017jelectrum.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_jelectrum_proto_BitcoinBlock_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_jelectrum_proto_BitcoinBlock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_jelectrum_proto_BitcoinBlock_descriptor,
        new java.lang.String[] { "Height", "Hash", "BlockData", });
    internal_static_jelectrum_proto_BitcoinBlockPack_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_jelectrum_proto_BitcoinBlockPack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_jelectrum_proto_BitcoinBlockPack_descriptor,
        new java.lang.String[] { "NewHeadHash", "StartHeight", "Blocks", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
